download tar balls instead of individual files

diff --git a/src/usr/sbin/sbopkg b/src/usr/sbin/sbopkg
--- a/src/usr/sbin/sbopkg
+++ b/src/usr/sbin/sbopkg
@@ -2469,17 +2469,21 @@ _curl_fail() {
 _curl_sync_package() {
     echo -n "$1-$2..."
     mkdir -p $REPO_DIR/$3
-    for file in $5; do	
-	echo -n "."
-	curl --silent --fail $REPO_LINK/$3/$file > $REPO_DIR/$3/$file || _curl_fail $?
-    done;
+#    for file in $5; do	
+#	echo -n "."
+#	curl --silent --fail $REPO_LINK/$3/$file > $REPO_DIR/$3/$file || _curl_fail $?
+#   done;
+    
+    echo "3 - $3"
+    echo "Downloading http://$REPO_LINK/$3.tar.gz > $REPO_DIR/$3.tar.gz" >> /tmp/log 
+    curl  --fail --silent "http://$REPO_LINK/$3.tar.gz" > "$REPO_DIR/$3.tar.gz" || _curl_fail $?
     echo "Ok"
 }
 
 _curl_slackbuilds_txt() {
     curl --fail $REPO_LINK/SLACKBUILDS.TXT.gz > $REPO_DIR/SLACKBUILDS.TXT.gz || return $?
     gunzip $REPO_DIR/SLACKBUILDS.TXT.gz
-    regexp="SLACKBUILD[ ]*([[:alpha:]]*): (.*)"
+    regexp="SLACKBUILD[ ]*([[:alnum:]]*): (.*)"
     while read line; do
 	if [[ $line =~ $regexp ]]; then	
 	    name=${BASH_REMATCH[1]}
@@ -2505,7 +2509,7 @@ _curl_slackbuilds_txt() {
 		    ;;
 		"MD5SUM" ) 
 		    package_md5sum="${BASH_REMATCH[2]}"
-		    ;;
+ 		    ;;
 		"SHORT DESCRIPTION" ) 
 		    package_shortdesc="${BASH_REMATCH[2]}"
 		    ;;
