actually download the files

diff --git a/src/usr/sbin/sbopkg b/src/usr/sbin/sbopkg
--- a/src/usr/sbin/sbopkg
+++ b/src/usr/sbin/sbopkg
@@ -2460,6 +2460,11 @@ _curl_changelog() {
     return 0
 }
 
+_curl_fail() {
+    echo "Curl Failed  : $1"
+    exit 10
+}
+
 # _curl_sync_package $package_name $package_version $package_location \
 #	    "$package_download" "$package_files"  $package_md5sum "$package_shortdesc"
 _curl_sync_package() {
@@ -2472,8 +2477,8 @@ _curl_sync_package() {
 	    count=0
 	    echo
 	fi
-	#curl --fail $REPO_LINK/$file
-	echo -n "..$file.."	
+	echo -n "$REPO_LINK/$3/$file.."	
+	curl --silent --fail $REPO_LINK/$3/$file > $REPO_DIR/$3/$file || curl_fail $?
     done;
     echo "Ok"
 }
